import time
import os

introSeconds = 8
time_division = 100.0
def runIntro():
    IntroFrame1(introSeconds,100.0)
    IntroFrame2(introSeconds,100.0)
    IntroFrame3(introSeconds,100.0)
    IntroFrame2(introSeconds,100.0)
    IntroFrame1(introSeconds,100.0)
    IntroFrame4(introSeconds,100.0)
    IntroFrame5(introSeconds,100.0)
    IntroFrame4(introSeconds,100.0)
    IntroFrame1(introSeconds,100.0)

def runSad():
    Sad1(30,100.0)
    Sad2(30,100.0)
    Sad1(30,100.0)
    Sad2(30,100.0)
    Sad1(30,100.0)
    Sad2(30,100.0)    

def runBlink():
    Blink1(30,100.0)
    Blink2(30,100.0)
    Blink1(30,100.0)
    Blink2(30,100.0)
    Blink1(30,100.0)
    Blink2(30,100.0) 
    Blink1(30,100.0)    

def IntroFrame1(time1, time2):
    os.system("cls")
    print("                                               _____         _____                   ")
    print("                                               \  _ \ _____ / _   /                  ")
    print("                          ____         ____     \    | ___ |     /                   ")
    print("                         /    \       /    \     >   | ___ |    <                    ")
    print("                        /      \     /      \   / _  |_____|  _  \                   ")
    print("                       |   /\   |   |   /\   | /____/       \_____\                  ")
    print("                       |  | o|  |   |  | o|  |                                       ")
    print("                       |  |  |  |   |  |  |  |                                       ")
    print("                       |   \/   |   |   \/   |                                       ")
    print("                        \      /     \      /                                        ")
    print("                         \____/       \____/                                         ")
    print("                                                                                     ")
    print("                               \    /                                                ")
    print("                                                                                     ")
    print("                    \__________________________/                                     ")
    print("                         V               V                                           ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    time.sleep(time1/time2)

    
def IntroFrame2(time1, time2):
    os.system("cls")
    print("                                               _____         _____                   ")
    print("                                               \  _ \ _____ / _   /                  ")
    print("                          ____         ____     \    | ___ |     /                   ")
    print("                         /    \       /    \     >   | ___ |    <                    ")
    print("                        /      \     /      \   / _  |_____|  _  \                   ")
    print("                       |  /\    |   |  /\    | /____/       \_____\                  ")
    print("                       | | o|   |   | | o|   |                                       ")
    print("                       | |  |   |   | |  |   |                                       ")
    print("                       |  \/    |   |  \/    |                                       ")
    print("                        \      /     \      /                                        ")
    print("                         \____/       \____/                                         ")
    print("                                                                                     ")
    print("                               \    /                                                ")
    print("                                                                                     ")
    print("                    \__________________________/                                     ")
    print("                         V               V                                           ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    time.sleep(time1/time2)
    
def IntroFrame3(time1, time2):
    os.system("cls")
    print("                                               _____         _____                   ")
    print("                                               \  _ \ _____ / _   /                  ")
    print("                          ____         ____     \    | ___ |     /                   ")
    print("                         /    \       /    \     >   | ___ |    <                    ")
    print("                        /      \     /      \   / _  |_____|  _  \                   ")
    print("                       | /\     |   | /\     | /____/       \_____\                  ")
    print("                       || o|    |   || o|    |                                       ")
    print("                       ||  |    |   ||  |    |                                       ")
    print("                       | \/     |   | \/     |                                       ")
    print("                        \      /     \      /                                        ")
    print("                         \____/       \____/                                         ")
    print("                                                                                     ")
    print("                               \    /                                                ")
    print("                                                                                     ")
    print("                    \__________________________/                                     ")
    print("                         V               V                                           ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    time.sleep(time1/time2)
    
def IntroFrame4(time1, time2):
    os.system("cls")
    print("                                               _____         _____                   ")
    print("                                               \  _ \ _____ / _   /                  ")
    print("                          ____         ____     \    | ___ |     /                   ")
    print("                         /    \       /    \     >   | ___ |    <                    ")
    print("                        /      \     /      \   / _  |_____|  _  \                   ")
    print("                       |    /\  |   |    /\  | /____/       \_____\                  ")
    print("                       |   | o| |   |   | o| |                                       ")
    print("                       |   |  | |   |   |  | |                                       ")
    print("                       |    \/  |   |    \/  |                                       ")
    print("                        \      /     \      /                                        ")
    print("                         \____/       \____/                                         ")
    print("                                                                                     ")
    print("                               \    /                                                ")
    print("                                                                                     ")
    print("                    \__________________________/                                     ")
    print("                         V               V                                           ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    time.sleep(time1/time2)    

def IntroFrame5(time1, time2):
    os.system("cls")
    print("                                               _____         _____                   ")
    print("                                               \  _ \ _____ / _   /                  ")
    print("                          ____         ____     \    | ___ |     /                   ")
    print("                         /    \       /    \     >   | ___ |    <                    ")
    print("                        /      \     /      \   / _  |_____|  _  \                   ")
    print("                       |     /\ |   |     /\ | /____/       \_____\                  ")
    print("                       |    | o||   |    | o||                                       ")
    print("                       |    |  ||   |    |  ||                                       ")
    print("                       |     \/ |   |     \/ |                                       ")
    print("                        \      /     \      /                                        ")
    print("                         \____/       \____/                                         ")
    print("                                                                                     ")
    print("                               \    /                                                ")
    print("                                                                                     ")
    print("                    \__________________________/                                     ")
    print("                         V               V                                           ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    time.sleep(time1/time2)    

def wiki1(time1, time2):
    os.system("cls")
    print("                                               _____         _____                   ")
    print("                                               \  _ \ _____ / _   /                  ")
    print("                          ____         ____     \    | ___ |     /                   ")
    print("                         /    \       /    \     >   | ___ |    <                    ")
    print("                        /      \     /      \   / _  |_____|  _  \                   ")
    print("                       |   /\   |   |   /\   | /____/       \_____\                  ")
    print("                       |  | o|  |   |  | o|  |                                       ")
    print("                   ----|  |  |  |---|  |  |  |--                                     ")
    print("                       |   \/   |   |   \/   |                                       ")
    print("                        \      /     \      /                                        ")
    print("                         \____/       \____/                                         ")
    print("                                                                                     ")
    print("                               \    /                                                ")
    print("                                                                                     ")
    print("                    \__________________________/                                     ")
    print("                         V               V                                           ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    time.sleep(time1/time2)
    
    
def Happy1(time1, time2):
    os.system("cls")
    print("                                               _____         _____                   ")
    print("                                               \  _ \ _____ / _   /                  ")
    print("                                                \    | ___ |     /                   ")
    print("                                                 >   | ___ |    <                    ")
    print("                                                / _  |_____|  _  \                   ")
    print("                          /\           /\      /____/       \_____\                  ")
    print("                         /  \         /  \                                           ")
    print("                        /    \       /    \                                          ")
    print("                       /      \     /      \                                         ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                               \    /                                                ")
    print("                                                                                     ")
    print("                    \__________________________/                                     ")
    print("                         V               V                                           ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    time.sleep(time1/time2)   


def Blink1(time1, time2):
    os.system("cls")
    print("                                               _____         _____                   ")
    print("                                               \  _ \ _____ / _   /                  ")
    print("                                                \    | ___ |     /                   ")
    print("                                                 >   | ___ |    <                    ")
    print("                                                / _  |_____|  _  \                   ")
    print("                                               /____/       \_____\                  ")
    print("                          \|/          \|/                                           ")
    print("                         --|--        --|--                                          ")
    print("                          /|\          /|\                                           ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                               \    /                                                ")
    print("                                                                                     ")
    print("                    \__________________________/                                     ")
    print("                         V               V                                           ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    time.sleep(time1/time2)       

def Blink2(time1, time2):
    os.system("cls")
    print("                                               _____         _____                   ")
    print("                                               \  _ \ _____ / _   /                  ")
    print("                                                \    | ___ |     /                   ")
    print("                                                 >   | ___ |    <                    ")
    print("                                                / _  |_____|  _  \                   ")
    print("                                               /____/       \_____\                  ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                               \    /                                                ")
    print("                                                                                     ")
    print("                    \__________________________/                                     ")
    print("                         V               V                                           ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    time.sleep(time1/time2)       
    
def OhNo1(time1, time2):
    os.system("cls")
    print("                                               _____         _____                   ")
    print("                                               \  _ \ _____ / _   /                  ")
    print("                                                \    | ___ |     /                   ")
    print("                                                 >   | ___ |    <                    ")
    print("                                                / _  |_____|  _  \                   ")
    print("                        _______      _______   /____/       \_____\                  ")
    print("                           |            |                                            ")
    print("                           |            |                                            ")
    print("                           |            |                                            ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                               \    /                                                ")
    print("                                                                                     ")
    print("                     __________________________                                      ")
    print("                         V               V                                           ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    time.sleep(time1/time2)      


def Sad1(time1, time2):
    os.system("cls")
    print("                                               _____         _____                   ")
    print("                                               \  _ \ _____ / _   /                  ")
    print("                          ____         ____     \    | ___ |     /                   ")
    print("                         /    \       /    \     >   | ___ |    <                    ")
    print("                        /      \     /      \   / _  |_____|  _  \                   ")
    print("                       |   /\   |   |   /\   | /____/       \_____\                  ")
    print("                       |  | o|  |   |  | o|  |                                       ")
    print("                       |  |  |  |   |  |  |  |                                       ")
    print("                       |   \/   |   |   \/   |                                       ")
    print("                        \      /     \      /                                        ")
    print("                         \____/       \____/                                         ")
    print("                                          /\                                         ")
    print("                         /\    \    /     \/                                         ")
    print("                         \/                                                          ")
    print("                     __________________________                                      ")
    print("                    /    V               V     \                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    time.sleep(time1/time2)    

def Sad2(time1, time2):
    os.system("cls")
    print("                                               _____         _____                   ")
    print("                                               \  _ \ _____ / _   /                  ")
    print("                          ____         ____     \    | ___ |     /                   ")
    print("                         /    \       /    \     >   | ___ |    <                    ")
    print("                        /      \     /      \   / _  |_____|  _  \                   ")
    print("                       |   /\   |   |   /\   | /____/       \_____\                  ")
    print("                       |  | o|  |   |  | o|  |                                       ")
    print("                       |  |  |  |   |  |  |  |                                       ")
    print("                       |   \/   |   |   \/   |                                       ")
    print("                        \      /     \      /                                        ")
    print("                         \____/       \____/                                         ")
    print("                         /\                                                          ")
    print("                         \/    \    /     /\                                         ")
    print("                                          \/                                         ")
    print("                     __________________________                                      ")
    print("                    /    V               V     \                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    print("                                                                                     ")
    time.sleep(time1/time2)  